theme: jekyll-theme-cayman
#name: diplomado bioinformática
title: Diplomado bioinformática y metagenómica
description: [Sitio de recursos de apoyo para el diplomado de bioinformática y metagenómica]
markdown: kramdown
plugins:
  - jemoji
